Menu/changes
dgraph-io/tutorial pull request #176
Opened 2020-06-15 08:07 UTC by shrutika2110

2020-06-15 08:15 UTC, shrutika2110 commented
@vardhanapoorv can you please merge the changes?

2020-06-18 15:08 UTC, MichelDiz requested changes
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/tutorial/176)* status: 0 of 525 files reviewed, 1 unresolved discussion (waiting on @MichaelJCompton and @shrutika2110)

___
*[published/404.html, line 31 at r1](https://reviewable.io/reviews/dgraph-io/tutorial/176#-MA6y-A4EKShfMf3OzJ1:-MA6y-A4EKShfMf3OzJ2:b-3byh95) ([raw file](https://github.com/dgraph-io/tutorial/blob/ed0291a5a55223dc93c642412bbd03a1fbe790a9/published/404.html#L31)):*
> ```HTML
>   
>   <title>404 Page not found</title>
>   <link href="http://localhost:8000//css/nucleus.css" rel="stylesheet">
> ```

Question, why this have 2 slashes? I fixed it in some previous PR, but now I wonder. Does it make any sense to have two slashes? I might break anything?


<!-- Sent from Reviewable.io -->

2020-06-18 15:12 UTC, MichelDiz commented
@danielmai can you check my previous question? just to make sure.

2022-04-29 07:36 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/dgraph-io/tutorial?pullRequest=176) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/dgraph-io/tutorial?pullRequest=176) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/dgraph-io/tutorial?pullRequest=176) it.</sub>

2024-07-18 11:21 UTC, closed without merging